### ISSUE TITLE
Not Linting while Typing

### ISSUE THREAD

**Issue by eshake01** [atom-community/linter#1045]
Hi,

I have "Lint as you type" enabled, but it won't lint as I type. I need to save it for there to be any linting.

**Comment by steelbrain** [comment]
Lint as you type only works if the provider supports it. If it doesn't, it'll only be triggered on save

**Comment by Arcanemagus** [comment]
Just to make sure this isn't a bug, which provider were you having issues with?

**Comment by steelbrain** [comment]
@Arcanemagus Sure! It's always nice to have a confirmation

**Comment by eshake01** [comment]
I installed the "base" linter package and "linter-htmlhint." That's the one I was having issues with

**Comment by steelbrain** [comment]
linter-htmllint seems to be linting the file on file system instead of text editor contents, it doesn't support lint on fly. See https://github.com/AtomLinter/linter-htmlhint/blob/14db83f989a5fddefeb305642e5985f215005cbf/lib/init.coffee#L34

@eshake01 Also I've replied to your email
I guess it's safe to say this is not a bug and working as intended
