### ISSUE TITLE
Autofix API

### ISSUE THREAD

**Issue by nmote** [atom-community/linter#1049]
I've implemented an autofix API for Nuclide diagnostics and I would like to settle on a similar API for the linter package. I know it may not be on the roadmap for you to implement but if we agreed on an API for the future, projects like `linter-eslint` could at least take advantage of this new functionality in Nuclide without using an unsanctioned API extension.

The API I came up with simply adds an optional `fix` field to the messages, of the type:

```
{
  oldRange: Range,
  newText: string,
  oldText?: string,
}
```

`oldText` is not required, but can be included to sanity-check the fix. How does this sound? If you like it, I will add support for it to Nuclide's linter adapter and put up a pull request with linter-eslint.

See also #418. I thought it would be better to open a new issue because that's pretty old and I don't have the ability to reopen it.

**Comment by Arcanemagus** [comment]
I'll leave it to @steelbrain to comment on the API suggestion itself, but I was curious how many linter programs you see that could support this data in the first place? Of the few that even provide a "fix" option that I know of, it looks like `eslint` is the only one that provides data back and doesn't only support running with a flag to fix on it's own.

**Comment by kepler0** [comment]
@Arcanemagus libclang gives this information. So presumably that's C, C++, Objective-C, and Objective-C++. As well as Swift due to it's LLVM ties. Add Rust on top of that. Seems like this is a good idea.

I'll also leave further API planning to @steelbrain.

**Comment by Arcanemagus** [comment]
Cool! Glad to hear it's more than just eslint as that's really nice information to have.

**Comment by steelbrain** [comment]
@nmote I like the concept, but I would suggest we do it in a backward compatible manner, for example, our current message object looks like this
```js
{
  type: 'Error',
  text: 'Some Error',
  range: [[line - 1, col - 1], [line - 1, col]]
}
```
We could add two new fields `replaceRange` and `replaceText` so it would become
```js
{
  type: 'Error',
  text: 'Some Error',
  range: [[line - 1, col - 1], [line - 1, col]],
  replaceRange: [[line -1, 0], [line -1 , col]],
  replaceText: 'Your line has been replaced'
}
```
I think it has a good name that we can guess it's purpose from and is backward compatible, what do you think?

**Comment by steelbrain** [comment]
After some discussion with @Arcanemagus, I am down with having a fix attribute for message. but a question I have in mind @nmote is, when we already have a range, why would we need `oldText` when we already have a `range`?

**Comment by Arcanemagus** [comment]
Just like `trace`, I'd prefer this was a single element myself.

@nmote Do you think a linter provider would ever need to specify multiple ranges to be replaced for a single message? If so how about this:

```text
{
  ...
  fix: [{range: Range, text: String}, {range ...}, ...]  
}
```

Or would that just complicate things with no linter provider ever utilizing it?

**Comment by nmote** [comment]
@steelbrain I'm fine with either flattening them or having a separate `fix` object, although I do slightly prefer the fix object. It's more obvious that you need to include all of the fix information or none if it's encapsulated into an object -- otherwise you have to document that if you provide `replaceRange` you must also provide `replaceText`, and it also presents fewer top-level fields to people who are just trying to get off the ground with their first linter.

The `oldText` can be used before applying the fix to sanity-check that it is being applied in the right place. Obviously that doesn't work if the `oldRange` is of zero length and therefore `oldText` would be empty, but in some cases it can provide another layer of safety. Perhaps I'm paranoid but it seems like a good idea to have as many checks as possible before changing people's code. But if you think that's overkill I'm fine leaving it off.

@Arcanemagus I thought about the possibility of multiple fixes, and perhaps it would be useful. However multiple fixes could always be consolidated into one larger fix, although then it would be more difficult to apply in the presence of unsaved changes (for example, if the user typed in the area between the two fixes). I understand the desire to future-proof but perhaps it's better to just have the single fix object and consider allowing arrays as well if the need arises?

**Comment by Arcanemagus** [comment]
Makes sense to me, we can always build it supporting arrays, and if we are fed an object just wrap it in an array.

**Comment by steelbrain** [comment]
@nmote I like your idea of having many checks before the code is replaced. 

I had some time to think about this today, and the most important question I have in mind for this is the UI. Atom is basically a text editor and packages like `linter` and `nuclide` make it an IDE. Therefore we should try to take the IDE approaches instead of text editor approaches whenever possible.

I have two decent ways in mind to handle the UI of fixes in linter or nuclide

1 - We add another line to the tooltip, that has a button on it and pressing that button fixes the current error. This includes mouse interaction, if we want to make it friendly for people who don't use much mouse, we'll have to add another command which they can bind to a key and press that key. 

This is the text editor approach and a really bad thing for UX as the user will have to remember the key binding for each package that they use. We also fear running out of keys this way. It is also unfriendly for users who don't touch their configs (majority of them don't). We can fix it here in the linter package and when we run into a similar issue in another package we'll have to re-invent the wheel there too.

2 - We create a base package, that allows packages like linter to hook into it. This package will host an  options menu that will be triggered by ctrl-space, It will have options that it's providers will add via API. Each time it's invoked, it's providers will be invoked based on the current scope and will tell it if they need to show an item in the list..

This is the IDE approach. Users won't have to touch their mouses, they won't have to configure any kind-of key mapping, and they'll get features from multiple packages including linter, all in one place. This will overall increase their productivity.

We are trying to make Atom an IDE and here's how an IDE handles this problem
![tooltips](https://cloud.githubusercontent.com/assets/4278113/12458560/35d7db3a-bfcc-11e5-8f33-09c8147035bf.png)

I have run into the need of such a package in other packages I'm maintaining as well, therefore I am strongly in favor of option 2, I already have that package in the works and will be releasing it soon.
Which option would you prefer?

Other than that, a minor nit I have in mind is that we could rename `oldRange` in the `fix` obj to `range` so it's structure would be this
```js
{
  range: Range,
  newText: string,
  oldText?: string,
}
```

**Comment by nmote** [comment]
I'll leave the UI up to you, but I'd like to point out that ctrl+space is already in use to manually activate autocomplete-plus: https://github.com/atom/autocomplete-plus/blob/master/keymaps/autocomplete-plus.cson

In Nuclide I've added a little `Fix` button to the popups. That's fine for now but I think you're right that the UX needs additional thought. One concern with the option two that you suggest is that it doesn't seem like it will be obvious that you have these options if you are just looking at the error. Unless I'm missing something you would still have to know the magic shortcut to get this menu.

Your screenshot raises an interesting question: What if there are multiple potential ways to fix a problem? How should we express that in the API? Currently providers like ESLint provide only a single fix, but I'm interested in getting fix information from Flow, for example, which has the potential to be more complex. However, what we have settled on will work for the majority of cases so I am in favor of moving forward with it and solving these problems later.

I am fine with the naming change from `oldRange` to `range`.

Since we seem to have reached a consensus I'll move forward with getting this into `linter-eslint`.

**Comment by steelbrain** [comment]
@nmote `ctrl-space` was actually a typo of `alt-enter`. The concept I have in mind is that linter itself will register as a provider to that package and will provide known fixes as a `Fix text using linter` option. The providers won't have to worry about it, they'll just have to provide a fix object.

This will only work for packages that need basic text replacement, like you said. Linter won't be able to satisfy packages that need advance replacements. Those packages will have to directly register themselves as providers to that package and list all available options.

That's fair IMO, what is your opinion?

**Comment by nmote** [comment]
Ah I see. That seems like a good first step for sure but at some point I think it would be worthwhile to allow providers to suggest different fixes without forcing each one to write the boilerplate to integrate with this menu.

At the risk of introducing feature creep, an API that satisfies all of the constraints we have discussed might look like this:

```
{
  text: string,
  filePath: string,
  ...
  fix: Array<{
    displayText: string,
    edits: Array<{
      range: Range,
      newText: string,
      oldText?: string,
    }>,
  }>,
}
```

So, the top-level `fix` array provides different options -- the user can select one of them. The `edits` array provides all of the edits that need to be applied to make the fix. The `displayText` property is shown to the user with that suggestion.

However I still would like to move forward with the simple API since this is added complexity that we don't yet have a concrete use for.

**Comment by steelbrain** [comment]
Agreed, lets implement the simpler API for now.

About the complicated API you suggested, I don't think that's a good idea for a number of reasons

1. This will complicate the diffing and parsing of linter messages
2. It will be an overkill because the number of packages that would use such advance features could be counted on my two fingers
3. The patch provided by provider will invalidate as soon as the user does anything within those ranges
4. It will create a lot of new objects that might never be used on each lint run, which for heavier use cases will make Atom a memory hog and GC will kick in more often causing loss of FPS

I have put together an example API of packages who would like an intentions entry, you can find it at https://gist.github.com/steelbrain/98feb0f293e1cc888343

That being said, I want to Thank you for bringing this idea to our attention, I'm sure a lot of people will enjoy this feature

**Comment by varemenos** [comment]
(I know I'm pretty much spamming about block decorations in this project's issues today but) they would be pretty useful if we able to displayed the diff of oldText and newText in a block above (or below) the line that needs fixing with a button that would trigger the fixing action.

**Comment by Arcanemagus** [comment]
@varemenos This will probably be brought into here through https://github.com/steelbrain/intentions and https://github.com/steelbrain/declarations.

**Comment by kepler0** [comment]
@Arcanemagus I think just `intentions`. `declarations` is more along the lines of a hyperclick competitor.

**Comment by Arcanemagus** [comment]
@kepler0 Good point, I just knew he had been working on related stuff in those packages :stuck_out_tongue:.

**Comment by steelbrain** [comment]
Actually both of you are correct, the intentions package has two types of API, one is highlight API that is used by declarations to provide a base jump-to-click API, other is menu API that is going to be used by linter to provide `Fix linter issue` menu item

**Comment by Arcanemagus** [comment]
Updated the [Wiki page](https://github.com/atom-community/linter/wiki/Linter-API) with what I believe was the current finalized API, if I didn't grab the right one please fix it!

**Comment by jergason** [comment]
Elm's compiler provides some warnings (top-level functions missing types, unused imports (see https://github.com/mybuddymichael/linter-elm-make/issues/22)) that could easily be parsed and turned in to fixes. This feature would make it pretty easy to add support for that, so I'm excited by this discussion.

**Comment by Arcanemagus** [comment]
@jergason There is nothing preventing you from implementing it in the linter provider package, and then when it is implemented here it will suddenly start working :wink.

**Comment by nmote** [comment]
I've also implemented this in Nuclide so you could use that for now if you'd like to try out autofix.

**Comment by Arcanemagus** [comment]
Btw, @nmote is the documentation in the Wiki aligned with what you implemented there? Based it off the discussion here and what was done in `linter-eslint`.

**Comment by nmote** [comment]
@Arcanemagus Yep, looks good to me.
