### ISSUE TITLE
Inline tooltips and split panes

### ISSUE THREAD

**Issue by deprint** [atom-community/linter#711]
![linter_problem](https://cloud.githubusercontent.com/assets/7817714/8580092/e5656b98-25b8-11e5-9473-89a7bc0d5196.png)

I encounter this problem when splitting my workspace to edit multiple files. As you can see, the tooltips are quite large and when a message is too long it does not break into multiple lines properly.

**Comment by steelbrain** [comment]
What provider are you using? That provider might wanna use our multi-line messages so they are wrapped by default and expanded only when the user clicks.

**Comment by deprint** [comment]
I'm currently working on [my own package](https://github.com/deprint/build-tools-cpp), but this happens with other linters as well. Here is an error from `linter-coffeescript`: 
![linter_problems2](https://cloud.githubusercontent.com/assets/7817714/8583382/7aa8b66a-25cd-11e5-97b1-3f5e0645a26d.png)
Also, I am not sure if multi-line messages solve this problem because the message itself is rather short (at least in my first example), often its the long file path that causes the message to be formatted in such a weird way.

**Comment by steelbrain** [comment]
I think we're gonna need a `min-width` of that panel.

**Comment by eboracus** [comment]
I was about to post a separate issue requesting a minimum width. :) So the panel floats with the cursor rather than being anchored to the right hand side.

Maybe a format of two lines for the message, with the file path & line/column on a separate line underneath to avoid problems with long file paths. And the 'at line 129 col 7' could certainly be shortened to just 129:7 I think without any loss of clarity/ambiguity.

**Comment by steelbrain** [comment]
The floating of panel with the cursor is intentional was implemented after a brief discussion. It was implemented to allow users to see below or write below the message.

**Comment by steelbrain** [comment]
This has been fixed in the latest release
