### ISSUE TITLE
Lint entire project.

### ISSUE THREAD

**Issue by envygeeks** [atom-community/linter#739]
It would be great if you guys would support linting an entire project so that if we install a new linter that was just made or anything of the sort we can have the linter backtrack on old files without having to reopen them one-by-one!

**Comment by nmalcolm** [comment]
+1 for this. Would have saved me a lot of time today.

**Comment by AsaAyers** [comment]
It sounds nice, but everything about the API was designed around linting an open buffer. 

Running your chosen linter from the cli is probably the best solution. They are designed to run over nested folders of code.

**Comment by envygeeks** [comment]
That same logic can be applied by this system too, since it has to launch a process at some.  I find it unbelievable that an API can't be adjusted slightly to fit in an extra trigger with a blob going to a linter and if it is then that is in an of itself a design problem IMO.

**Comment by steelbrain** [comment]
@envygeeks There are actually more efficient ways to handle this problem, instead of spawning a process of each file, a lot of linters like coffeelint or HH typechecker lint the whole directory when you point them at it, we could use that. But it's something to considered for the future API versions, that's why I've marked it as a feature request with a low-priority, I could increase the priority, but I am gonna need votes for that :)

**Comment by envygeeks** [comment]
@steelbrain I never said launch a linter for each file, sorry if I implied that.

**Comment by AsaAyers** [comment]
I never said the API can't be changed. Only that from the ground up everything involved in the API is about linting buffers, not linting files.

Linting the project can't simply be layered onto the API efficiency. We have to add a second mechanism that linter-coffeelint, linter-eslint, etc will all have to opt into. It's going to be a significant amount of work requiring coordination and cooperation of multiple projects. 

Until that happens I recommend using the existing tools that have already been designed and built for this exact purpose.

**Comment by envygeeks** [comment]
"Significant amount of work" and "opt-in" contradict one another... but I understand.

**Comment by AsaAyers** [comment]
I'm not talking about you as a user opting in. I'm talking about me as the
maintainer of linter-coffeelint opting to use the new project api.

Does that clear up the contradiction?

**Comment by steelbrain** [comment]
@AsaAyers @envygeeks Cool down you two :sweat_smile:

**Comment by AsaAyers** [comment]
:confused:?

**Comment by envygeeks** [comment]
I meant that too.  When you state something is opt-in for linter-coffeelint and then claim it's a significant amount of work, that contradicts the purpose of opting-in, that's mandatory API implementations but if you truly made it opt-in then the work wouldn't be so significant because then people like me could see the new API and implement it in the projects that are important to us when we want it and take a lot of the load off you.

**Comment by steelbrain** [comment]
@AsaAyers Do you recall when we discussed about creating a generic daemon, that works with but is not limited to linter, that scans the entire project for errors and relints the files on change, that truly makes the Project tab project-scoped, and because it's not gonna be in core linter but a separate project, I think it's a great idea. Let me know what do you think.

**Comment by AsaAyers** [comment]
I think a separate project is fine. It just doesn't belong in this project.

**Comment by envygeeks** [comment]
You mean this project shouldn't be linting?

**Comment by AsaAyers** [comment]
Care to try again without intentionally quoting me out of context?

**Comment by envygeeks** [comment]
In order to intentionally quote out of context I have to quote you.  I didn't quote you, I was responding to what you were implying to me, which is exactly what I said.  There is no reason to split it out into an entirely different project, that kind of decoupling is over zealous to say the least because more than 70% of the code can probably be shared (if not more.) -- That's a rough guess and could be entirely wrong.

**Comment by envygeeks** [comment]
All I am saying is, I keep hearing everybody fight against something that should be drastically simple if only the basic logic is applied, don't treat globs as single files, and adjust a few minor pieces to consider entire directories going into a linter and not just a single file.  I'm not trying to be mean to you, I'm being mean to the resistance to something that is well for lack of a better statement "easy", it doesn't need it's own project, it doesn't need much to get it done, it just needs an adjustment of the logic at it's most primitive and very little of that.

**Comment by AsaAyers** [comment]
Sorry, that was the wrong logical fallacy. You're making a straw man
argument. https://youtu.be/cGZkCPo7tC0

When I get home I'll restate my whole argument

**Comment by envygeeks** [comment]
You have no fucking idea what you are talking about, so instead of fighting with an idiot I'm going to close this ticket and fork the project and complete what I want myself it's easier than dealing with dumb people.  I do hope you have a lovely day.

**Comment by envygeeks** [comment]
Sorry, I don't mean dumb people, I mean dumb person.

**Comment by AsaAyers** [comment]
The reason we integrate linters into editors is to lint the code you're actively working on. If you're using a linter consistently there are only two ways to produce lint errors/warnings:

1. You care working on some bit of code and your editor is helping you spot these before you commit
2. You change the rules of the linter now the whole codebase needs to be scanned.

If you want to find your lint errors when you change the rules you should go run the linter directly.

As it stands today, we can only lint open buffers. Here are the options as I see them

Simple
=====

Just open every file in the project and it'll get linted. I think this probably won't scale.

Change API (Lint text instead of buffers)
===============================

If the API linted strings instead of `Editor`s we could pass the text and avoid having to create 1,000 editors for a 1,000 file project. All we have to do is finish getting all 70 linters to use the API we have now, and then turn around and make all of them change again.

New API (Lint directories)
===================

We make a new API where each linter can opt into linting directories. Should the core linter manage ignored files/directories? How should this work? If you want to ignore `foo/bar/` but you have `foo/a.coffee` `foo/baz/b.coffee` you can't just tell the linter to lint `foo/`, you either push the work of ignoring `foo/bar` out into `linter-*` or the core has to determine the minimal subset of files/directories to pass to get everything linted.

Other project
==========

We push all of this complexity into another project. I don't care how it does any of it, it only needs to report results back to linter.

**Comment by diesire** [comment]
Lint entire project would be nice. 

Until today I though lint an entire project was an included feature :open_mouth:, so the **Project** button in the UI should be **Open files** or something like that to avoid confusion...

> @AsaAyers @envygeeks Cool down you two :sweat_smile:

**Comment by diesire** [comment]
> The reason we integrate linters into editors is to lint the code you're actively working on. If you're using a linter consistently there are only two ways to produce lint errors/warnings:
> 
> You care working on some bit of code and your editor is helping you spot these before you commit
> You change the rules of the linter now the whole codebase needs to be scanned.
> If you want to find your lint errors when you change the rules you should go run the linter directly.
> 
> As it stands today, we can only lint open buffers. Here are the options as I see them

I think this is a good point and must be in the docs as a reminder but remember this atom plugin is a thin layer on top of the linters, and lintting a folder with source files is a common task for most of them.

> # New API (Lint directories)
> 
> We make a new API where each linter can opt into linting directories. Should the core linter manage ignored files/directories? How should this work? If you want to ignore foo/bar/ but you have foo/a.coffee foo/baz/b.coffee you can't just tell the linter to lint foo/, you either push the work of ignoring foo/bar out into linter-* or the core has to determine the minimal subset of files/directories to pass to get everything linted.

I think you can delegate all this stuff into the linter itself. Most of them have config files where you can define exclude paths or other things. The only change at API level should be passing a `Buffer` or a `path` and let linter play with it

**Comment by AsaAyers** [comment]
I haven't been involved in Linter for many months now. It looks like I may not eve be a member here any more, but since you want to talk about it I figured I can try to help clarify my opinion.

It is a common task. One that belongs in your precommit hook and your continuous integration server. If you aren't committing code that fails the rules you defined for your project, there is no reason to have your editor lint the whole project. On the occasion that you change a rule you have options. Just run your shell command and go open the files that fail now. 

> The only change at API level should be passing a Buffer or a path and let linter play with it

As far as the actual linting process `linter`'s job is to pass a `Buffer` to `linter-whatever` and then save the results. The heavy lifting that `linter` does is actually in displaying the results. `linter-whatever` can be implemented in any way the author wants. You could write a linter in JavaScript that only functions inside Atom. I think that seems like a bad idea, but you can.

When `linter` executes on an open buffer, it passes that buffer to `linter-coffeelint`. `linter-coffeelint` extracts the text from the buffer (because it may not be on disk yet) and lints that code. Without changing the API `linter` needs to open every file in the project in a buffer and pass them all to `linter-coffeelint`. Many linters just dispatch out to a shell command, but this didn't make sense to me with `coffeelint` already being (compiled to) JavaScript. Instead it uses `require('coffeelint')` and executes functions. Passing a path means that `linter-coffeelint` has to be redesigned.

**Comment by Arcanemagus** [comment]
FYI: [atom-build](https://github.com/noseglid/atom-build) handles almost all the functionality that was being talked about here, from what I understand. (Specifically because it runs the lint commands you should have as part of your build process as @AsaAyers mentioned above!)

**Comment by nodefiend** [comment]
+ 1

**Comment by skylize** [comment]
> #### Simple
> Just open every file in the project and it'll get linted. I think this probably won't scale.
> 
> #### Change API (Lint text instead of buffers)
> If the API linted strings instead of Editors we could pass the text and avoid having to create 1,000 editors for a 1,000 file project. All we have to do is finish getting all 70 linters to use the API we have now, and then turn around and make all of them change again.

Just brainstorming here. I think I generally agree this would be nice, but doesn't really deserve a high priority.

How about opening just 1 extra buffer to lint every file in the project one-at-a-time, collating errors into a single list as we go?
* Prevents needing drastic changes to the architecture. No need for opt-in, can simply provide the service automatically to existing linters.
* Prevents pounding the CPU too hard, because sequential reading of files makes the hard disk a natural throttle.
* Scalability is limited by wait-time for project linting. Small projects will be plenty fast, by virtue of being small. Larger projects can lint in the background while you continue working because we're not hogging all the system resources. So even though it's obviously not perfect, it should be at least an "okay" experience for all users.

**Comment by envygeeks** [comment]
For certain linters linting an entire project is easy... exp: rubocop, you can skip any and all arguments and it'll lint the entire project and all the files in it from the .rubocop.yml (which should really be enforced,) for other linters I don't know, but I know for certain linters it's drastically easy.
