### ISSUE TITLE
API v1.2

### ISSUE THREAD

**Issue by steelbrain** [atom-community/linter#763]
Things to consider

 - [x] Linters have to provide a name field
   - We have a config where the user can choose to show the name field `all the time` or `when needed` or `off`
   - `all the time` would mean that the name is shown regardless of the numbers of the providers for a syntax
   - `when needed` would mean that the name would only be shown when there's more than one linters on that grammar
   - `off` would hide the name no matter what
 - [ ] Linters will optionally set `lintsDirectories` flag to true
   - We will add an option in tree view to lint that specific directory
   - We will add a new tab in the tab container that will show errors in that specific directory (complex, eh! :muscle: )
   - The user will see an x icon on that tab that they can click to remove it
   - That icon will be deleted on restart/refresh

We all agree on the first one, 2nd one has my vote too but I would like to get your suggestions/thoughts on it.
/cc @atom-community/linter-contributors

**Comment by nelson6e65** [comment]
:+1:

**Comment by AsaAyers** [comment]
I don't know why you're calling it 1.2. [The API](https://github.com/atom-community/linter/blob/master/package.json#L18) is 1.0.0. If we're following semver and the name becomes required then it needs to be 2.0.0

lintsDirectories
===========

Why does the user need the whole project linted? If you've been using a linter then files you don't have open should never have issues because you aren't committing code with lint errors. This leaves two possibilities 1) you're adding linting to an existing project 2) you've changed linting rules int he middle of an existing project. In my opinion both of these are exceptional circumstances where the user should solve it using external tools.

Alternatively, since we provide a standardized API someone could create a different project that consumes our linters and then runs them against the whole project. It would be very inefficient, but if you're only doing it when changing/adding linter configuration it doesn't matter much. If I were to design such a thing I'd have it iterate through the files of the project showing you editors where you have things to fix. When you fix the last lint error the editor can close and open the next file for you to work on.

If you do proceed with making it part of `linter` I think it's going to add more complexity than you think. How often should you lint the whole project? What happens when a file is modified outside of atom?How does the user ignore specific folders? Since JavaScript/CoffeeScript is often transpiled it produces a generated file that could, but should not be, linted. I'm sure there are more, but this is what I came up with in a few minutes.

**Comment by wackywendell** [comment]
I would just like to point quickly to issue #773. To summarize the differences between that and this: it would be really nice if wherever the name is showed, it could also show "No Linter Found" when, well, no linter is found for that file type.

**Comment by egeland** [comment]
I'd like to add a +1 for the "show which, if any, linter is being used" as per @wackywendell 's comment above.

**Comment by steelbrain** [comment]
What are you opinions about hover tooltips?
/cc @atom-community/linter-contributors

**Comment by steelbrain** [comment]
Some features have been implemented, others have been opened in separate issues, some have been discouraged. Closing this now.
