### ISSUE TITLE
Add option to disable linting if the config file is not found

### ISSUE THREAD

**Issue by stevemao** [atom-community/linter#818]
just like https://github.com/AtomLinter/linter-jscs/blob/master/index.js#L24-L29
But I believe it would be better to put it in core as all linters should have such an option.

**Comment by steelbrain** [comment]
We are not going to allow that, and are going to remove from those who already support it.
The reason is that there are too much possibilities for where the config could be, it could be in your `$HOME/.somethingrc`, or embedded in your package.json or in your Project root. 
Copy/pasting all the logic from all the linters would increase the effort it takes to maintain a linter.
So closing this in favor of https://github.com/atom-community/linter/issues/744
