### ISSUE TITLE
linter:togglePanel not working

### ISSUE THREAD

**Issue by jacobmischka** [atom-community/linter#857]
The toggle panel command seems to be doing nothing at all for me, either by using the fuzzy finder or double clicking the open tab. Toggle lint does work in disabling the lint, but it does not enable it again if activated again. That might be intended behavior, I'm not sure. I'm not getting any error messages and nothing is showing up in devtools. Tested with linter-pylint and linter-jshint packages.

Atom 1.0.7
linter 1.4.3
Arch Linux x64

**Comment by Arcanemagus** [comment]
Running `Linter:Toggle` turns off the entire linter package. Turning it back on will simply enable it again, but all your previous messages would have been cleared. To get messages to show again you would need to trigger a lint.

`Linter:TogglePanel` seems to be broken for me as well, but double clicking the _linter_ open tab (Line | File | Project) does work to hide the panel. So that is a definitely a bug.

**Comment by jacobmischka** [comment]
Oh, that's the tab I'm supposed to click. My mistake, that is working for me as well, sorry. And okay, thank you for explaining the linter toggle's behavior.

**Comment by steelbrain** [comment]
Fixed by https://github.com/atom-community/linter/pull/861
