### ISSUE TITLE
linter panel takes up space when empty

### ISSUE THREAD

**Issue by yomed** [atom-community/linter#876]
The `<linter-panel>` tag seems to have `padding: 3px` by default. This causes it to take up space when it is empty. In my case, it creates odd UI effects when switching to iterm2. When iterm2 is active, the `<atom-panel>` parent of `<linter-panel>` is `display:none`, so switching between these tabs causes UI glitching.

**Comment by steelbrain** [comment]
A gif explaining it would be nice

**Comment by yomed** [comment]
![output_pq7yng](https://cloud.githubusercontent.com/assets/3595986/9700142/90e5c7b6-53ad-11e5-96a8-fc383e18841f.gif)

**Comment by steelbrain** [comment]
@yomed well, that's kind-of a limitation of the latest diffing algorithm. It only happens when you switch to a pane that's not a text editor, if both of those were text editors, it won't change at all.

We could've workaround it with something like `linter-panel:empty`, but because in our latest diffing method, we don't remove messages from the DOM when they are hidden (say with a scope that disallows them temporarily), so it's gonna be a bit complicated. I would love to have any ideas/suggestions

**Comment by yomed** [comment]
I don't know much about how linter is setup internally. Since you can't use `linter-panel:empty`, could you remove the default padding on `<linter-panel>` and put it on `<linter-message`>s instead? Or it would that have unintended side effects?

**Comment by steelbrain** [comment]
@yomed We could remove that padding, but that padding would be removed all the times then, even when the panel has some messages, it wouldn't look good from a UI point of view.

**Comment by yomed** [comment]
Right, what I mean is that maybe you could put it on the children elements instead, since having it on the parent doesn't take contents into account.

**Comment by steelbrain** [comment]
I would be happy to accept a PR for this
