### ISSUE TITLE
Add ability to resize linter panel

### ISSUE THREAD

**Issue by jolsenmultiad** [atom-community/linter#880]
First: thank you for a wonderful Atom package!

Sometimes I use atom with linter on a netbook with a small screen and would like to easily toggle or control how much editor space is available.

It would be nice to have one or both of these options:
1) Add a traditional GUI-style collapse/expand button so user can collapse the linter panel to regain editor space for code and expand it when wanting to view linter messages (I know toggling can be done via command palette, this is for a on-screen GUI way of toggling)
2) Ability to dynamically resize the panel (via click and drag) in order to control how many max linter messages are displayed at once

Thanks again

**Comment by steelbrain** [comment]
You can click the active tab button to collapse the panel, re-click to expand it. Making it resizable is an appleaing idea. Would you like the resize to persist across projects or globally?

**Comment by jolsenmultiad** [comment]
I was not aware the File status bar item was  button and that it toggled the panel. Thank you!

At the moment, I don't have a strong preference for resizing persistence. I'm leaning toward a global persistence because no matter what project I'm editing on a small screen, I would think I'd want the same amount of editor space. Unless you get more feedback from other users indicating otherwise, I'd say go with whatever is easier to implement. 

Thank you again.

**Comment by steelbrain** [comment]
I am personally in the favor of making it persistent globally instead of making it project-specific. Because we often resize due to spacing problems or personal tastes and our screen sizes and/or tastes don't change over projects.
The difficult part in implementing this is not the scope of persistence, but the resizing events and all that. so difficulty is not a factor here.

I am busy in my personal projects these days so just fixing bugs, not implementing any new features but this is definitely a thing that I've personally wanted sometimes. I'll be implementing it with priority.

About the tab buttons, Maybe we should document that somewhere? We also have a `linter:togglePanel` command by the way, so you can just map it to a key and press that key and be happy with it.

**Comment by russpowers** [comment]
:+1: 

This would be very useful!  I'm using the linter in on-the-fly mode, and it often causes the error panel to grow and shrink when typing.

**Comment by steelbrain** [comment]
A confirmed fix is up in #910
